### ISSUE TITLE
specify readme directions

### ISSUE THREAD

**Issue by DJDevon3** [tio/tio.msys2#1]
In windows 10 I had to use
`cd /c/msys64/mingw64/mingw-w64-libinih`

It took me a while before I realized I had to download the contents of the github zip file into the mingw64 directory. I think that should be specified in the directions too for beginners like me. :/ Something like:

Click on Download, Download the zip folder to your c:/msys64/mingw64 directory. If the mingw64 folder doesn't exist create it.

**Comment by lundmar** [comment]
Yes, you have to clone the repository or download and extract the zip. I've added a comment to hint this. You can put it in any place accessible to your mingw env.
